sudo: false
language: scala
scala:
  - 2.11.11
  - 2.12.4
jdk:
- oraclejdk8
cache:
  directories:
    - "$HOME/.m2/repository" 
    - "$HOME/.sbt" 
    - "$HOME/.ivy2"     
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test